# Generated by Django 3.0.7 on 2020-07-05 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfinance', '0004_conf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='receita',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
