# Generated by Django 3.0.7 on 2020-07-11 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfinance', '0006_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
