# Generated by Django 3.0.7 on 2020-07-11 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfinance', '0007_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=300)),
                ('password', models.CharField(max_length=300)),
            ],
        ),
    ]
