# Generated by Django 3.0.7 on 2020-07-14 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfinance', '0008_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='situacao',
            field=models.CharField(max_length=255),
        ),
    ]
