# Generated by Django 3.0.7 on 2020-07-14 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfinance', '0010_auto_20200714_0408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='classificacao',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='receita',
            name='situacao',
            field=models.CharField(max_length=255),
        ),
    ]
